### ISSUE TITLE
Building on Alpine 3.6 fails

### ISSUE THREAD

**Issue by robertdebock** [square/sudo_pair#22]
Hi,

I'm [trying to build sudo-pair on many distributions](https://travis-ci.org/robertdebock/ansible-role-sudo-pair) but run into a few issue.

On Alpine 3.6 the building fails with this error:
```
error: manifest path `/tmp/sudo-pair/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

These is the environment:
```
/ # cat /etc/alpine-release 
3.6.2
/ # cargo --version
cargo 0.18.0
/ # rustc --version
rustc 1.17.0
/ # gcc --version
gcc (Alpine 6.3.0) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

On Alpine 3.7 the error is different, as Alpine 3.6 is a bit older, I think it's reasonable to accept this error as a known issue and not fix it, unless it's easy to solve.

Kind regards,

Robert de Bock.

**Comment by stouset** [comment]
This is due to a combination of: me using lints only available on more recent versions of rust, enabling a lint that warns if a lint is enabled that the compiler doesn't understand, and failing to build when there are warnings.

Failing to build on warnings is only really useful in CI, so I've opened a PR that only enables that in Travis.
