### ISSUE TITLE
Publish new version on crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [square/sudo_pair#57]
Or is this project basically dead? Latest release was 2 years ago according to crates.io

**Comment by stouset** [comment]
It’s not dead, there just haven’t been any bugs worth fixing or features worth adding. There’s a PR open to allow usernames and groupnames in addition to uids/gids, but it hasn’t seemed like a priority for the original requester since I finished the feature, and if nobody is enthusiastic about wanting it I’d just as soon not merge it.

If and when there are some bugs and or features requests, I’m more than happy to address them!

**Comment by ignatenkobrain** [comment]
Then would be nice if you could update dependencies to their latest versions and release a new version.

**Comment by ignatenkobrain** [comment]
This is only thing which does not properly compile on Fedora because of missing dependnecies.

**Comment by stouset** [comment]
I'm not sure what you're getting at with dependencies. There are no dependencies to update as of the latest release.

```sh
$ cat sudo_plugin-sys/Cargo.toml
[dependencies]
libc = '0'

$ cat sudo_plugin/Cargo.toml 
[dependencies]
libc            = '0'
error-chain     = '0'
sudo_plugin-sys = { version = "1.1", path = "../sudo_plugin-sys" }

$ cat sudo_pair/Cargo.toml 
[dependencies]
libc        = '0'
error-chain = '0'
sudo_plugin = { version = "1.1", path = "../sudo_plugin" }
```

None of these dependencies are out of date. The latest libc is still `0.x` and the latest error-chain is `0.x`. There are no other dependencies in these three crates.

**Comment by ignatenkobrain** [comment]
@stouset 

https://crates.io/crates/sudo_plugin-sys → bindgen ^0.37
