### ISSUE TITLE
Wishlist: Session Logging

### ISSUE THREAD

**Issue by stephanbuys** [square/sudo_pair#9]
Hi, any plans on the roadmap to include logging into this? It would be great to have the session logged to a log management system or equivalent.

**Comment by stouset** [comment]
It's something I'm planning on doing, but I'm not sure if it will ever be a feature of the plugin, part of a second plugin, or if it will just be a responsibility of the approval command.

Doing this with the approval command is *really* easy (at least conceptually, but there are important details around how to handle disconnects, etc.). If you just pipe the `socat` output to `script`, you get a fully replayable, timestamped archive of the session that you can store for later analysis.

**Comment by trevor-vaughan** [comment]
In the spirit of 'a thing for a task', it might be good to make sure this plays nicely with tlog https://github.com/Scribery/tlog for logging.

**Comment by stouset** [comment]
The more I think about this, the more I believe it should be a second plugin (you can enable multiple I/O plugins simultaneously). It probably wouldn't be very hard to do, since the `sudo_plugin` crate already abstracts away the gory details.

I had been intending to output logs in [`scriptreplay(1)`](http://man7.org/linux/man-pages/man1/scriptreplay.1.html) format, but it's probably not much extra work to have an option to write `tlog`-compatible output either.

**Comment by stouset** [comment]
sudo has this built-in as a separate logging plugin.
